### ISSUE TITLE
Do you need any help building/fixing something?

### ISSUE THREAD

**Issue by herou** [toposware/hash#27]
Substrate/rust developer here

Contributor on different Substrate/Rust repos: https://github.com/herou
1- Converted substrate all the recipes from frame v1 o v2 : https://github.com/JoshOrndorff/recipes/pull/471 (It took me 6 months)
2- Winner of one of Web3 grants and delivered it on time: https://github.com/w3f/Grant-Milestone-Delivery/pull/599

Let me know!

**Comment by Nashtare** [comment]
Thanks @herou for the proposition! We are not actively developing on this repository anymore, hence there is no urgent/real need for this at the moment, but it would still be beneficial to have concrete instantiations of different hash functions for similar parameters, at least over the small Goldilocks field, to get concrete performance comparison.

If you want to work on one, feel free to do so and I'd be happy following up!

**Comment by herou** [comment]
@Nashtare thank you for quick reply. Which repo are you currently working? I am looking forward to contribute on that if possible. Please, let me know.

**Comment by Nashtare** [comment]
Hey @herou, you should have received an email from our lead software engineer to discuss those details. I'm therefore closing this issue. Feel free to reopen it if you feel like needed.
